//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashraful_MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Ashraful_MVCProject.CustomAttributes;

    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int AuthorID { get; set; }
        [Required(ErrorMessage = "Name Required")]


        public string AuthorName { get; set; }
        //[Required(ErrorMessage = "Email Required")]

        //[EmailAddress]
        public string Email { get; set; }
        //[Required(ErrorMessage ="Required")]
        public Nullable<int> Phone { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date)]
        [CustomDate(ErrorMessage = "Birth Date must be less than or equal to Today's Date")]
        public Nullable<System.DateTime> BirthDate { get; set; }

        //[Required(ErrorMessage ="Address Required")]
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
