//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashraful_MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerRegistraion
    {
        public int CustomerRegistraionID { get; set; }

        [Required(ErrorMessage ="This Field Is Required")]
        [StringLength(30,MinimumLength =3,ErrorMessage ="Name should be in between 3-30")]

        public string CustomerName { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]

        public string Gender { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> Phone { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [Range(18,90,ErrorMessage ="Age should be in between 18-90")]
        public Nullable<int> Age { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
