//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashraful_MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Supplier
    {
        public int SupplierID { get; set; }
        [Required(ErrorMessage ="Required")]
        public string SupplierName { get; set; }
        [Required(ErrorMessage ="Required")]
        [EmailAddress]

        public string Email { get; set; }
        [Required(ErrorMessage ="Required")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> Phone { get; set; }
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
